# Generated by Django 2.2.12 on 2022-04-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='report_date',
            field=models.DateTimeField(),
        ),
    ]
