# Generated by Django 2.2.12 on 2022-04-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0002_auto_20220428_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField()),
                ('media', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('link', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', models.CharField(blank=True, max_length=4000, null=True)),
            ],
        ),
    ]
