# Generated by Django 2.2.12 on 2022-04-30 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0008_auto_20220430_0303'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=['summary', 'link']
        ),
    ]
