# Generated by Django 2.2.12 on 2022-04-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0009_auto_20220430_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='report_date',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set(),
        ),
    ]
