# Generated by Django 2.2.12 on 2022-04-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0010_auto_20220430_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
