# Generated by Django 2.2.12 on 2022-04-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0012_auto_20220430_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='report_date',
            field=models.DateTimeField(),
        ),
    ]
