# Generated by Django 2.2.12 on 2022-05-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0014_auto_20220501_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='score',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='covid',
            name='active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covid',
            name='active_diff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covid',
            name='fatality_rate',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='covid',
            name='recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covid',
            name='recovered_diff',
            field=models.IntegerField(default=0),
        ),
    ]
