# Generated by Django 2.2.12 on 2022-05-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0015_auto_20220503_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='score',
            field=models.DecimalField(decimal_places=6, default=10.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='covid',
            name='fatality_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
