# Generated by Django 2.2.12 on 2022-05-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0017_auto_20220504_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='confirmed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
