# Generated by Django 2.2.12 on 2022-05-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0018_auto_20220504_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='active',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='active_diff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='confirmed_diff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='deaths_diff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='recovered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='recovered_diff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
