# Generated by Django 2.2.12 on 2022-05-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0019_auto_20220504_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='fatality_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
